version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

  web1:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./www/web1:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=fraymamertoesquiu.edu.ar,www.fraymamertoesquiu.edu.ar
      - LETSENCRYPT_HOST=fraymamertoesquiu.edu.ar,www.fraymamertoesquiu.edu.ar
      - LETSENCRYPT_EMAIL=jorgezarate@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt

  web2:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./www/web2:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=info.fraymamertoesquiu.edu.ar
      - LETSENCRYPT_HOST=info.fraymamertoesquiu.edu.ar
      - LETSENCRYPT_EMAIL=jorgezarate@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt

volumes:
  certs:
  html:
  vhostd: 
  acme: